In [ ]:
#Sobel filtresi bir görüntü işleme tekniğidir ve genellikle kenar tespiti amacıyla kullanılır. Kenar tespiti, bir görüntüdeki nesnelerin sınırlarını veya konturlarını belirleme
#işlemidir.
#Sobel filtresi, bir görüntü üzerindeki yoğunluk gradyanlarını vurgulamak için kullanılır. Yoğunluk gradyanı, bir pikselin renk yoğunluğundaki değişikliği ifade eder. Sobel filtresi,
#bir görüntüyü x ve y eksenlerinde türev alarak kenar bilgisini elde eder.
#Sobel operatörü genellikle bir matris (kernel) olarak temsil edilir. İki farklı matris, biri dikey kenarları belirlemek için (Sobel dikey filtresi), diğeri ise yatay kenarları
#belirlemek için (Sobel yatay filtresi) kullanılır. Bu matrisler şu şekildedir:

#Sobel dikey filtresi:
# [-1 0 1]
# [-2 0 2]
# [-1 0 1]

#Sobel yatay filtresi:
# [-1 -2 -1]
# [ 0  0  0]
# [ 1  2  1]

#Bu matrisler, bir pikselin etrafındaki piksellerin yoğunluk değerleri arasındaki farkları ölçer. Bu farklar, kenarlarda yoğunluk değişimlerini vurgular. Sobel filtresi, bu matrisleri
#giriş görüntüsü üzerine kaydırarak her pikselin kenar gücünü hesaplar.

#Genellikle, Sobel filtresi uygulandıktan sonra elde edilen sonuçlar genellikle kenar tespiti için kullanılır. Yüksek gradyan değerleri, kenarlara karşılık gelirken, düşük değerler
#genellikle arka plana karşılık gelir. Bu, nesne sınırlarını belirlemek ve görüntü üzerindeki önemli özellikleri ortaya çıkarmak için kullanışlıdır.

In [ ]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

# Görüntüyü yükle
image = cv2.imread('görüntü.jpg', cv2.IMREAD_GRAYSCALE)

# Sobel filtresini uygula
sobelx = cv2.Sobel(image, cv2.CV_64F, 1, 0, ksize=3)
sobely = cv2.Sobel(image, cv2.CV_64F, 0, 1, ksize=3)

# Kenar gücünü ve yönetimini hesapla
magnitude = np.sqrt(sobelx**2 + sobely**2)
angle = np.arctan2(sobely, sobelx)

# Kenarları görselleştir
plt.figure(figsize=(10, 5))

plt.subplot(2, 2, 1), plt.imshow(image, cmap='gray')
plt.title('Original'), plt.xticks([]), plt.yticks([])

plt.subplot(2, 2, 2), plt.imshow(sobelx, cmap='gray')
plt.title('Sobel X'), plt.xticks([]), plt.yticks([])

plt.subplot(2, 2, 3), plt.imshow(sobely, cmap='gray')
plt.title('Sobel Y'), plt.xticks([]), plt.yticks([])

plt.subplot(2, 2, 4), plt.imshow(magnitude, cmap='gray')
plt.title('Magnitude'), plt.xticks([]), plt.yticks([])

plt.show()
